**Objective:** This notebook is created to practice NumPy, a core Python library used in Data Analytics and Data Science. The focus is on understanding how NumPy handles numerical data efficiently using arrays and how it supports data manipulation, calculations, and basic analytics operations.

**Why NumPy?**
NumPy (Numerical Python) provides:

High-performance n-dimensional arrays

Fast mathematical and statistical operations

Efficient memory usage compared to Python lists

A strong foundation for libraries like Pandas, SciPy, and Scikit-learn

**Topics Covered in This Notebook:**
Creating NumPy arrays (1D & 2D)

Array indexing and slicing

Shape, size, and data types

Basic arithmetic operations

Aggregation functions (sum, mean, min, max)

Reshaping and broadcasting

Practical examples related to data analytics

**Learning Approach:**
Learn by hands-on practice

Write clean and readable code

Focus on real-world data analytics use cases

Build a strong foundation for Pandas and data visualization

**Tools Used:**
Python

NumPy

Google Colab

**Outcome:**
By completing this notebook, I aim to gain confidence in using NumPy for data manipulation and numerical analysis, which is essential for Data Analyst and Data Science roles.

In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.0.2


In [3]:
# 1-D array
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [4]:
# 2-D array
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
print(arr1.ndim) # number of dimensions
print(arr2.ndim)
print(arr1.shape) # shape of array
print(arr1.size) # total elements
print(arr1.dtype) # data type

1
2
(6,)
6
int64


In [6]:
#Indexing
print(arr1[0])
arr1[-1]
#2D Indexing
print(arr2[0,1]) #Prints 0th row , column 1
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(data[0,1]) # Prints 0 row , 1st col
print(data[1]) # Full row
print(data[:,2]) #Full col

1
2
2
[4 5 6]
[3 6 9]


In [9]:
#Slicing - selecting a range of data.
print(arr1[1:4]) #Prints elements from index 1 to 3
print(arr1[1:4])
print(arr1[:3])
print(arr1[3:])
print(arr1[::2])    # step size

[2 3 4]
[2 3 4]
[1 2 3]
[4 5 6]
[1 3 5]


In [10]:
#Basic Mathematical Operations
print(arr1 + 2)
print(arr1 - 2)
print(arr1 * 2)
print(arr1 / 2)

[3 4 5 6 7 8]
[-1  0  1  2  3  4]
[ 2  4  6  8 10 12]
[0.5 1.  1.5 2.  2.5 3. ]


In [11]:
# Aggregation Functions
import numpy as np
print(np.sum(arr1))
print(np.mean(arr1))
print(np.min(arr1))
print(np.max(arr1))



21
3.5
1
6


In [12]:
import numpy as np
np.arange(1,15) #Creating array in a smarter way

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
np.zeros(5) # Will generate 5 zeroes
np.zeros((3,4)) # 3 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
print(np.ones(3))
print(np.ones((2,3)))

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
np.full((3,3),7) # Prints 3 rows 3 columns and value is 7

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [17]:
#Creating Random Numbers
np.random.rand(5)

array([0.29252991, 0.49352646, 0.3539219 , 0.08782826, 0.98713288])

In [18]:
np.random.randint(1,100,size=10) #Print 10 number in between 1 to 100

array([11, 44, 60, 85, 52, 38,  7, 88, 35, 61])

In [19]:
arr = np.arange(1,13)
print(arr)
arr.reshape(3,4) #Reshaping Rows × Columns must match total elements.

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
arr.reshape(3,4).flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
# Shape & Axis Concept
data = np.array([[1,2,3],[4,5,6]])
print(data.sum(axis=0)) # Performs column wise summation 1+4 , 2+5 ,3+6
print(data.sum(axis=1)) # Performs row wise summation 1+2+3 , 4+5+6

[5 7 9]
[ 6 15]


In [22]:
data1=np.array([1,2,3,4,5])
print(data1>3) # Condition
print(data1[data1>3]) # Filtering
print((data1>2) & (data1<5)) # Multiple conditions
print(data1[(data1>2) & (data1<5)])

[False False False  True  True]
[4 5]
[False False  True  True False]
[3 4]


In [23]:
# Modifying Values Using Conditions
data1[data1<2] = 0
print(data1)

[0 2 3 4 5]


In [24]:
# Basic Statistical Functions
data = np.array([5,10,15,20,25])
print(np.sum(data))
print(np.min(data))
print(np.max(data))
print(np.mean(data))
print(np.median(data))

75
5
25
15.0
15.0


In [25]:
# Variance & Standard Deviation
print(np.var(data))
print(np.std(data))

50.0
7.0710678118654755


In [26]:
# Percentiles
print(np.percentile(data,25))
print(np.percentile(data,50))
print(np.percentile(data,75))

10.0
15.0
20.0


In [28]:
# Correlation
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])
np.corrcoef(x,y)

array([[1., 1.],
       [1., 1.]])

In [29]:
marks = np.array([[25,30,35,40],
 [20,25,30,26],
  [34,28,34,40]])
np.mean(marks,axis=0) #column i.e subject wise
np.mean(marks,axis=1) #column i.e student wise

array([32.5 , 25.25, 34.  ])