### 📘 NumPy Real-World Data Analysis
This notebook applies NumPy concepts to real-world scenarios such as student marks and sales data analysis. It focuses on row-wise and column-wise computations, filtering data using conditions, identifying insights, and performing basic data cleaning to simulate real analytics tasks.


In [1]:
import numpy as np

In [2]:
marks = np.array([[50,55,68],
                  [90,73,63],
                  [80,95,89],
                  [60,48,90], #cols = subjects
                  [45,64,72]]) # rows = students
print(marks.shape) # shape tells the velue of number of rows and number of columns
print(marks.ndim)

(5, 3)
2


In [3]:
x=np.mean(marks,axis=0) #col wise i.e , sujects mean , Average marks per subject
print(x)
y=np.max(marks,axis=0) #col wise i.e , students max , Highest marks per subject
print(y)
z=np.min(marks,axis=0) #col wise i.e , students min , Lowest marks per subject
print(z)

[65.  67.  76.4]
[90 95 90]
[45 48 63]


In [4]:
total = np.sum(marks, axis = 1) # Total marks per student
print(total)
avg = np.mean(marks, axis = 1) # Average marks per student
print(avg)

[173 226 264 198 181]
[57.66666667 75.33333333 88.         66.         60.33333333]


In [5]:
#Identify Toppers & Weak Students
#Students scoring average > 85
avg_marks = np.mean(marks,axis=1)
print(avg_marks[avg_marks>85])
print(marks[marks<70]) #Students who scored below 70 in any subject

[88.]
[50 55 68 63 60 48 45 64]


In [6]:
# Replace marks < 35 with 35
marks[marks<35] = 35
print(marks)

[[50 55 68]
 [90 73 63]
 [80 95 89]
 [60 48 90]
 [45 64 72]]
