### 📘 NumPy File Handling & Pre-Pandas Preparation
This notebook demonstrates how to work with external CSV files using NumPy. It includes reading and writing data, performing analysis on file-based datasets, and understanding the limitations of NumPy, thereby creating a smooth transition toward using Pandas for advanced data analytics.


In [1]:
import numpy as np

In [2]:
#Create Sample CSV
data = np.array([[101,5000,2], # employee id , salary , experience
                 [102,5500,7],
                 [103,6000,3],
                 [104,7700,6],
                 [105,5330,1]])
np.savetxt("employees.csv",data,delimiter=",",fmt="%d")

In [4]:
# Read CSV Using NumPy
emp_data = np.loadtxt("employees.csv",delimiter=",",dtype=np.int64)
print(emp_data)

[[ 101 5000    2]
 [ 102 5500    7]
 [ 103 6000    3]
 [ 104 7700    6]
 [ 105 5330    1]]


In [5]:
# Analyze File Data
# Average salary
avg_salary = np.mean(emp_data[:,1])
print(avg_salary)

5906.0


In [6]:
# Highest experience
high_exp = np.max(emp_data[:,2])
print(high_exp)

7


In [15]:
# Employees with salary > 5500
high_salary_employees = data[data[:, 1] > 5500]
high_salary_employees

array([[ 103, 6000,    3],
       [ 104, 7700,    6]])